#!/usr/bin/env /bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

apt install authbind -y

for port in 80 443
do
  touch /etc/authbind/byport/$port
  chown $1 /etc/authbind/byport/$port
  chmod 500 /etc/authbind/byport/$port
done
