#!/usr/bin/env /bin/bash

DOMAIN=$1.joshandrews.xyz

if [ $# = 1 ]; then
    SERVICE=$1
else
    SERVICE=$2
fi

#sudo certbot certonly --standalone -d $DOMAIN

cat > conf/$1.conf << EOF
server {
    listen 443 ssl http2;
    server_name $DOMAIN;

    ssl_certificate /etc/letsencrypt/live/joshandrews.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/joshandrews.xyz/privkey.pem;

    location / {
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
        proxy_ssl_session_reuse off;
        proxy_set_header Host \$http_host;
        proxy_cache_bypass \$http_upgrade;
        proxy_redirect off;
        proxy_pass http://$SERVICE;
    }
}
EOF
