version: '3'
volumes:
    adguard-conf:
    adguard-work:
    nextcloud:
    homeassistant-config:
    db:

secrets:
    db_root: 
        file: ./secrets/db_root
    db: 
        file: ./secrets/db
    tunnel: 
        file: ./secrets/tunnel

services:
    adguard:
        image: adguard/adguardhome
        restart: unless-stopped
        volumes:
            - adguard-conf:/opt/adguardhome/conf
            - adguard-work:/opt/adguardhome/work
        ports:
            - 53:53 # DNS
            - 67:67 # DHCP
            - 3000:3000 # Install
    db:
        image: mariadb:10.6
        restart: always
        command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
        volumes:
            - db:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root
            MARIADB_PASSWORD_FILE: /run/secrets/db
            MARIADB_DATABASE: nextcloud
            MARIADB_USER: nextcloud
        secrets:
            - db
            - db_root

    nextcloud:
        image: nextcloud
        restart: unless-stopped
        links:
            - db
        volumes:
            - nextcloud:/var/www/html
        ports:
            - 3001:80
        environment:
            MARIADB_PASSWORD_FILE: /run/secrets/db
            MARIADB_DATABASE: nextcloud
            MARIADB_USER: nextcloud
            MARIADB_HOST: db
        secrets:
            - db

    homeassistant:
        image: homeassistant/home-assistant
        restart: unless-stopped
        ports:
            - 80:8123
        volumes:
            - homeassistant-config:/config
            - /etc/localtime:/etc/localtime:ro

    tunnel:
        image: cloudflare/cloudflared
        restart: always
        command: tunnel run
        environment:
            TUNNEL_TOKEN: