version: '3.8'
volumes:
    adguard-conf:
    adguard-work:
    nextcloud:
    homeassistant-config:
    db:

secrets:
    db_root: 
        file: ./secrets/db_root
    db: 
        file: ./secrets/db
    tunnel: 
        file: ./secrets/tunnel

services:
    web:
        image: nginx
        restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.d/default.conf
            - ./index.html:/var/www/html/index.html
        ports:
            - 80:80

    adguard:
        image: adguard/adguardhome
        restart: unless-stopped
        volumes:
            - adguard-conf:/opt/adguardhome/conf
            - adguard-work:/opt/adguardhome/work
        ports:
            - 53:53 # DNS
            - 67:67 # DHCP

    db:
        image: mariadb:10.6
        restart: always
        command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
        volumes:
            - db:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root
            MARIADB_PASSWORD_FILE: /run/secrets/db
            MARIADB_DATABASE: nextcloud
            MARIADB_USER: nextclo
        secrets:
            - db
            - db_root

    nextcloud:
        image: nextcloud:fpm
        restart: unless-stopped
        links:
            - db
        volumes:
            - nextcloud:/var/www/html
        environment:
            MARIADB_PASSWORD_FILE: /run/secrets/db
            MARIADB_DATABASE: nextcloud
            MARIADB_USER: nextcloud
            MARIADB_HOST: db
        secrets:
            - db

    homeassistant:
        image: homeassistant/home-assistant
        restart: unless-stopped
        volumes:
            - homeassistant-config:/config
            - /etc/localtime:/etc/localtime:ro

    tunnel:
        image: cloudflare/cloudflared
        command: TUNNEL_TOKEN=$${< /run/secrets/tunnel} && tunnel run --no-autoupdate  
        restart: always
        secrets:
            - db