version: '3.9'
volumes:
    adguard-conf:
    adguard-work:
    nextcloud:
    homeassistant:

secrets:
    db_root: ./secrets/db_root.txt
    db: ./secrets/db.txt
    tunnel: ./secrets/tunnel.txt

services:
    web:
        image: nginx
        deploy:
            restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.d/default.conf
            - ./index.html:/var/www/html/index.html
        ports:
            - 80:80

    adguard:
        image: adguardhome
        deploy:
            restart: unless-stopped
        volumes:
            - adguard-conf:/opt/adguardhome/conf
            - adguard-work:/opt/adguardhome/work
        ports:
            - 53:53 # DNS
            - 67:67 # DHCP

    db:
        image: mariadb:10.6
        deploy:
            restart: always
        command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root
            MYSQL_PASSWORD_FILE: /run/secrets/db
            MYSQL_DATABASE: nextcloud
            MYSQL_USER: nextcloud

    nextcloud:
        image: nextcloud:fpm
        deploy:
            restart: unless-stopped
        links:
            - db
        volumes:
            - nextcloud:/var/www/html
        environment:
            MYSQL_PASSWORD_FILE: /run/secrets/db
            MYSQL_DATABASE: nextcloud
            MYSQL_USER: nextcloud
            MYSQL_HOST: db

    homeassistant:
        image: homeassistant/home-assistant
        deploy:
            restart: unless-stopped
        volumes:
            - haconf:/config
            - /etc/localtime:/etc/localtime:ro

    tunnel:
        image: cloudflare/cloudflared
        command: TUNNEL_TOKEN=${< /run/secrets/tunnel} && tunnel run 
        deploy:
            restart: always
        