version: '3'
volumes:
    nextcloud:
    homeassistant-config:
    db:
    bitwarden:

secrets:
    db_root: 
        file: ./secrets/db_root
    db: 
        file: ./secrets/db
    ddns_api:
        file: ./secrets/ddns_api
    pihole:
        file: ./secrets/pihole
    nextcloud:
        file: ./secrets/nextcloud
    
services:
    homelab:
        image: ghcr.io/gethomepage/homepage:latest
        ports:
            - 3000:3000
        volumes:
            - ./contexts/homepage:/app/config # Make sure your local config directory exists
            - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
        environment:
            PUID: 
            PGID:
            HOMEPAGE_FILE_PIHOLE_KEY: /run/secrets/pihole 
            HOMEPAGE_VAR_PIHOLE_KEY:
            HOMEPAGE_VAR_PIHOLE_IP:
            HOMEPAGE_VAR_LAPTOP_IP:
            HOMEPAGE_VAR_HOMELAB_IP:
            HOMEPAGE_FILE_NEXTCLOUD_KEY: /run/secrets/nextcloud
        dns:
            - $HOME_DNS
        secrets:
          - pihole
          - nextcloud

    website:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./contexts/website/conf:/etc/nginx/conf.d:ro
            - /etc/letsencrypt/:/etc/letsencrypt:ro
        links:
            - cloud
            - iot
            - homelab

#    sshd:
#        build: contexts/sshd
#        restart: always
#       ports:
#            - "2222:22"
#        volumes:
#            - ~/.ssh:/root/host-ssh:ro
#            - nextcloud:/volumes/nextcloud:rw
#            - homeassistant-config:/volumes/hs-config:rw
#            - db:/volumes/db

    db:
        image: mariadb:10.6
        restart: always
        command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
        volumes:
            - db:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root
            MARIADB_PASSWORD_FILE: /run/secrets/db
            MARIADB_DATABASE: nextcloud
            MARIADB_USER: nextcloud
        secrets:
            - db
            - db_root

    cloud:
        image: nextcloud
        restart: always
        links:
            - db
        volumes:
            - nextcloud:/var/www/html
        environment:
            MARIADB_PASSWORD_FILE: /run/secrets/db
            MARIADB_DATABASE: nextcloud
            MARIADB_USER: nextcloud
            MARIADB_HOST: db
        secrets:
            - db

    iot:
        image: homeassistant/home-assistant
        restart: always
        volumes:
            - ./contexts/iot:/config
            - /etc/localtime:/etc/localtime:ro

    projectsideline:
        image: nginx
        restart: always
        volumes:
            - /home/josh/git/project-sideline/website/build:/var/www/html

    ddns:
        build: contexts/ddns
        restart: always
        environment:
            DOMAIN: "*.joshandrews.xyz"
            # Get these from: https://www.cloudflare.com/a/account/my-account
            AUTH_KEY_FILE: /run/secrets/ddns_api
            EMAIL: joshurtree@gmail.com
            # Get the Zone ID from: https://www.cloudflare.com/a/overview/<your-domain>
            IDENTIFIER: 047b332798401343fe0d00705f7f6324
            # Get the existing identifier for DNS entry: https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records
            DNS_ZONE: 77f01c20b84a2667279a50acba998187
             
    glances:
        image: nicolargo/glances:latest-full
        restart: always
        environment:
            GLANCES_OPT: -w
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
        pid: host