# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /config/custom_components/lovelace-card-mod/card-mod.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
    use_x_forwarded_for: true
    trusted_proxies:
        - 172.0.0.0/8

shell_command:
  laptop_test: ssh -i /config/id_rsa -o 'StrictHostKeyChecking=no' root@acer-laptop -- touch ~/test.txt
  laptop_poweroff: ssh -i /config/ssh/id_rsa -o 'StrictHostKeyChecking=no' root@acer-laptop -- poweroff

sensor:
  # Minimal configuration of the standard time and date sensor
  - platform: time_date
    display_options:
      - date
      - time